### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by gjnoonan** [julmud/phpDVDProfiler#1]
Not an issue, so of course feel free to close it.

I was a user of DVDProfiler, and active in the community during the 00's. I started using phpDVDProfiler when it was initially released.

I've been feeling nostalgic over the weekend and my mind got thinking of the joy of the whole DVD collecting scene back then, so I went searching and came across this :-)

I no longer have access to DVDProfiler, but I am happy to contribute to this if you're going to start active development; What are your plans?

**Comment by julmud** [comment]
Thanks for your interest. I currently have no plan. My only aim was to make it work with PHP 7.2, and it's been done with my second commit. ;-)

There's currently two areas which could be further investigated / implemented: I did a brief test of running it with PHP 7.4 and there were some errors / notices which should be corrected, and there seems to be [some problems with 4K content](http://www.invelos.com/Forums.aspx?task=viewtopic&topicID=477881&PageNum=2&messageID=2832055#M2832055) too, but I haven't looked at it at all yet (as I don't own any 4K discs, this was less a priority for me ;-) ).

If any of those areas interest you, or if you have any other idea, feel free to work on them.
