### ISSUE TITLE
[question] gallery stays empty

### ISSUE THREAD

**Issue by udo1toni** [julmud/phpDVDProfiler#29]
As I recently updated my system, I also made an update to latest release (v_20200130). Works fine, but the gallery stays empty (i.e. although there is a page selector, there are no pictures). 
Pictures in the profiles are ok though (thumbnail and full picture), but no luck in the gallery.

I'm pretty sure I missed some major part when installing, but I have absolutely no idea what I missed...

**Comment by julmud** [comment]
Are you sure the gd extension is active in your PHP environment?

**Comment by udo1toni** [comment]
Sorry, missed the answer...

Somehow the correct module wasn't installed any longer.

**Comment by udo1toni** [comment]
Er... so, closing the thread... ;)
