### ISSUE TITLE
Location of current favicon code seems incorrect

### ISSUE THREAD

**Issue by MotyerJM** [julmud/phpDVDProfiler#41]
phpDVDProfiler version: **v20230108**
Browser 1: **Brave** secure browser version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)
Browser 2: **Iridium** secure browser version 2021.12 (Official Build) (64-bit)
Browser 3: **Microsoft Edge** version 108.0.1462.76 (Official build) (64-bit)

Was unable to get phpDVDProfiler's favicon to display in any browsers' tabs.

There is a favicon that comes with phpDVDProfiler, **/gfx/favicon.ico**, with a size of 32x32px.

Located in index.php between lines 159-164, and specifically on line # 163, is the following call to that favicon (**my bolding** on that line below) :
```
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=windows-1252">
<title>CoverScan</title>
<link rel=stylesheet type="text/css" href="format.css.php">
**<link rel="SHORTCUT ICON" href="/gfx/favicon.ico">**
</head>
```

However, all browsers that I had tried display only what seems to be a default (globe) icon when no specific favicon is found.

I converted that favicon to a PNG, but kept the same name, so favicon.png and changed line 163 to be:
`<link rel="icon" type="image/png" href="/gfx/favicon.png">`
However, I still saw only the default globe icon on browser tabs.

Through some experimentation, I discovered that if I add that favicon.png line below line 1458, **AND remove** the leading slash in front of gfx, the favicon is then displayed in the browser tabs:
```
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=windows-1252">
  <title>$CurrentSiteTitle</title>
  <link rel="icon" type="image/png" href="gfx/favicon.png">
  $rssfeed
  <script type="text/javascript" src="top.js"></script>
</head>
```
Just thought I would mention the above, in case you wish to add that favicon capability in a future release... no idea for how many years the favicon had not been displayed, but I don't recall seeing it for many years, if ever.

And extremely happy with your new v20230108, thank you again.

**Comment by julmud** [comment]
Thanks. I'd never noticed there was a favicon.ico file. I've actually recreated it, so it can be used in higher resolution for mobile browsers too.
Regarding the first forward slash, usually favicons are always given as an absolute path from the web root. So I've added a path detection mechanism so the full path can be used in the resulting HTML document.
Not yet sure whether or not I want to "force" this favicon on all sites using phpDVDProfiler... I personally quite like the fact that I can put a favicon at the root of my webserver and have it being used by default for all the sub-directories. I'll probably revisit this feature and make it a configuration option in siteconfig before releasing.

**Comment by MotyerJM** [comment]
- phpDVDProfiler version: **v20230108-1a70048**
- PHP version = 8.2.1

I was not implying for you to update the favicons at this time, as I already had unique favicons for each of my collections... I was only mentioning this for a possible update of the favicons in a future release in the coming year.  But thank you for taking the time to do so.

I have added the changes in your 1a70048 to all of my collections, and all is working great, thank you.

I would think that some (if not most) of your users would have a single phpDVDProfiler collection, so the default favicon would suffice.  In my case, I have 5 different phpDVDProfiler collections, so with a single **identical** favicon for each of my collections, when I have browser tabs open for more than 1 of my collections, it is impossible for me to know which tab is for which collection when I have many tabs open, because the width of the tabs is too narrow for me to read from the $sitetitle which collection is which.  This is why I have a **unique** favicon for each of my collections.

I like the idea that you have, of placing a configuration option for it in siteconfig.

Thanks again.
