### ISSUE TITLE
php8.3 does not seem to work

### ISSUE THREAD

**Issue by DJDoena** [julmud/phpDVDProfiler#47]
My provider upgraded me to php8.3 and since then I only got a blank page.

https://doena-soft.de/phpdvdprofiler/

here's my PhpInfo https://doena-soft.de/pi.php

**Comment by julmud** [comment]
@DJDoena I just upgraded my local installation to PHP 8.3.15 and I don't have any problems with my phpDVDProfiler installation. As your installation returns a 500 error (server error), it should have logged a message in the server's error log. Do you have access to the error log of the server and could you provide me with the error message? It would really help me understand what's going wrong with your installation.

I've had a quick look at your phpinfo output (thanks for that) and all the mandatory extensions (intl, mysqli, mbstring, gd) are present. I don't see any obvious differences with my phpinfo either... So I'm at a bit of a loss as to how to help you further, unless you can provide me with the error message from the server logs. Sorry.

**Comment by DJDoena** [comment]
[25-Dec-2024 14:32:47 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /www/htdocs/djdoena/phpdvdprofiler/global.php:36
Stack trace:
#0 /www/htdocs/djdoena/phpdvdprofiler/rss.php(82): include_once()
#1 {main}
  thrown in /www/htdocs/djdoena/phpdvdprofiler/global.php on line 36
  
  https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

**Comment by julmud** [comment]
@DJDoena Thanks for the error message. The call to `get_magic_quotes_gpc` has been removed from the phpDVDProfiler code in November 2022 and released with version v_20230102. Are you sure you're running the latest version (https://github.com/julmud/phpDVDProfiler/releases/tag/v_20230807)?

**Comment by DJDoena** [comment]
very weird, I did this (I even still had the zip file on drive). But now I've actively killed everything online but

```
imagecache           Directory
images               Directory	 
collection.xml       XML document	   
localities.xod       file
localsiteconfig.php  PHP script
```

and now it works...
